### ISSUE TITLE
Auto-mirrored from SF?

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#1]
Will this be an automatically mirrored repo, like https://github.com/svn2github/nikkhokkho?

**Comment by javiergutierrezchamorro** [comment]
Not yet familiar with svn2github, but think so.

**Comment by TPS** [comment]
https://github.com/svn2github/nikkhokkho has automatically mirrored (even commits ~24 hours), but this repo is still bare of files.…

**Comment by TPS** [comment]
Hey, @javiergutierrezchamorro, try the new official GitHub cloning facility @ https://github.com/new/import .…  It'll probably work better than https://github.com/svn2github for your use-case, I hope!

**Comment by TPS** [comment]
@javiergutierrezchamorro Good to see the repo up-to-date! ☺  I plan to close this after a week or so, when I can tell if the cloning continues to update. :smile:

**Comment by TPS** [comment]
Unfortunately, as https://github.com/svn2github/nikkhokkho/commits/master shows, _this_ repo isn't automatically keeping up-to-date.…  Any ideas?

**Comment by javiergutierrezchamorro** [comment]
No idea sorry.

**Comment by TPS** [comment]
I've contacted @GitHub.  They hopefully have a solution.

**Comment by javiergutierrezchamorro** [comment]
Thank you very much @TPS.

**Comment by TPS** [comment]
No problem!  The official solution to this, if using an external _`git`_ repo, is @ https://help.github.com/articles/about-github-mirrors/. (@GitHub has told me the previously linked tool is for _static_ importing.)  Is that something you can adapt for your `svn` repo?  Else, I'm anyway continuing the conversation with @GitHub.

**Comment by TPS** [comment]
No problem!  The official solution to this, if using an external _`git`_ repo, is @ https://help.github.com/articles/about-github-mirrors/. (@GitHub has told me the previously linked tool is for _static_ importing.)  Is that something you can adapt for your `svn` repo?  Else, I'm anyway continuing the conversation with @GitHub.

Alternatively, here's a gist @ticean created to solve exactly this: https://gist.github.com/ticean/1556967
FYI, @ticean, there're a _lot_ of comments there you're not getting due to https://github.com/isaacs/github/issues/21

**Comment by TPS** [comment]
Just FYI: I just found that this is an _old_ problem, & https://github.com/isaacs/github/issues/415 has been tracking it.

**Comment by TPS** [comment]
@javiergutierrezchamorro Another idea for this: since https://github.com/svn2github/nikkhokkho is keeping up-to-date so well, maybe delete the _code_ (keeping issues, of course) from https://github.com/javiergutierrezchamorro/nikkhokkho, & replace with a ReadMe, saying this is an _issues-only_ repo ([I'm a regular on another, so maybe you could copy a little from that](https://github.com/AdguardTeam/AdguardForAndroid/)) & point to https://github.com/svn2github/nikkhokkho as a _read-only_ mirror.

**Comment by javiergutierrezchamorro** [comment]
Yes, it is a pitty having two github repositories, and also the SVN and support at Sourceforge.
Will need some time to address everything.
