### ISSUE TITLE
RFE: Optionally add support to decrypt PDFs (& related) before processing

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#12]
@javiergutierrezchamorro Another way to handle [the recent PDF handling updates](https://github.com/svn2github/nikkhokkho/compare/61f3f55f22...54f3008104) would be to _optionally_ decrypt PDFs before optimizing, using, e.g., [`qpdf --decrypt`](http://qpdf.sourceforge.net/files/qpdf-manual.html). Binaries are @ https://sourceforge.net/projects/qpdf/files/qpdf/; most recent source _may_ be @ https://github.com/qpdf/qpdf.

_N.B._: The above docs mention the need for a password to decrypt.  I've found that `qpdf` can handle many kinds of "encrypted" PDFs (e.g., those with "edit" passwords, but no "open" passwords) _without_ supplying such!  GhostScript often barfs at these, but not _after_ processing with `qpdf`.  YMMV.…

**Comment by TPS** [comment]
[`pdfclean` (part of mupdf tools)](http://mupdf.com/downloads/) will reportedly also do this with same kinds of PDFs [while doing garbage collection via `-ggg`](http://manpages.ubuntu.com/manpages/precise/man1/pdfclean.1.html).

**Comment by javiergutierrezchamorro** [comment]
Will think about it. Problem is it will require a per file password to be stored somewhere, which will require lots of changes.

Do not like the idea of prompting the user interactively, since it will prevent automation via command line. So maybe the solution is a setting to ask or not for passwords.

**Comment by javiergutierrezchamorro** [comment]
As for pdfclean, I guess this is already done by ghoscript and smpdf. Have you performed any tests with it?

**Comment by TPS** [comment]
I meant this ___only___ for PDFs which _don't_ need interactive processing, where the edit-password/DRM can be removed auto-magically.

**Comment by TPS** [comment]
> Have you performed any tests with it?

Yes, running `pdfclean -ggg` usually will _inflate_ an already-FileOptimized PDF, but then re-running FileOptimizer will generally shrink it further than before `pdfclean`.

**Comment by javiergutierrezchamorro** [comment]
Did additional tests, and using pdfclean -ggg -z before Ghostcript and smpdf, seems to get better ratios, so it is now added in r567 (https://sourceforge.net/p/nikkhokkho/code/567/).

**Comment by TPS** [comment]
Thanks, @javiergutierrezchamorro!

Here, it's https://github.com/svn2github/nikkhokkho/commit/53d03ec4b48dfb9240c3ff2719857cb501d184eb.
