### ISSUE TITLE
Update tidy-html5

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#14]
@javiergutierrezchamorro According to https://github.com/svn2github/nikkhokkho/commits/master/FileOptimizer/Win64/Debug/Plugins64/tidy.exe, last commit to these binaries was v5.1.4, but both https://github.com/htacg/html-tidy.org.binaries/tree/gh-pages/binaries & https://github.com/htacg/tidy-html5/releases show v5.2.0 as the current latest.  Though, w/ 37+ more commits since then, it's likely another release should be forthcoming soon.

I'm trying to track down a bug w/ the version included in FO (_feels_ similar to https://github.com/javiergutierrezchamorro/nikkhokkho/issues/9#issuecomment-243999006, though I've no real evidence other than an immediate crash _every_time run), & I'm hoping this update will fix it.

**Comment by javiergutierrezchamorro** [comment]
You are right. My mistake!
Do not know why I used 5.1.14, if 5.2.0 was available since months ago. It is updated in r569.

**Comment by TPS** [comment]
I will test on next release whether the crash persists.  If so, I may file @ https://github.com/htacg/tidy-html5/issues & refer link here.

https://github.com/svn2github/nikkhokkho/commit/bb2ce2039047fd5a0a4ea51b7d0c31b335e0efac is the v5.2.0 commit here.  Thanks!

**Comment by javiergutierrezchamorro** [comment]
Agree. Currently enabling HTML/SVG optimization is controlled with Enable Tidy. Which in fact not only enables tidy, but also Leanify. So it is not well named. But the concept is correct. Optimizing HTML or SVG, even if behaviour gets unchanged, they are not furthermore editable, at least manually. This is why it is not enabled by default.

**Comment by TPS** [comment]
Just FYI, upgrading to FO v9.10.1575 solved my issue w/ `tidy-html5` crashing. :bow:

**Comment by javiergutierrezchamorro** [comment]
Thanks for your confirmation @TPS!

**Comment by TPS** [comment]
@javiergutierrezchamorro Latest tidy-html5, since a few days ago, is v5.4.0 @ https://github.com/htacg/tidy-html5/releases.

**Comment by TPS** [comment]
Nm, I misread the date. You got it @ https://github.com/svn2github/nikkhokkho/commit/3e233d854863e25249a83282bb9ad2d6623e5761. 😳
