### ISSUE TITLE
[Shift]-[Del] Doesn't Work Anymore under v9.20.1585

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#16]
@javiergutierrezchamorro <kbd>Shift</kbd>-<kbd>Del</kbd> doesn't delete selected items anymore under v9.20.1585.  I _do_ still use it, along with the new <kbd>F5</kbd> functions.

**Comment by javiergutierrezchamorro** [comment]
Sorry for that. Remove selected files was always disabled.

It was a regression when I implemented classic Windows UI together with Ribbon in 9.00, and was never noticed before.

It is now fixed on r589 (https://sourceforge.net/p/nikkhokkho/code/589/)

**Comment by TPS** [comment]
It _did_ work on this previous build, though, & I used it extensively.

Thanks for fixing! :smile:
