### ISSUE TITLE
Update PNGWolf-Zopfli

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#17]
@javiergutierrezchamorro: v1.1.2 @ https://github.com/jibsen/pngwolf-zopfli/releases/

P.S.: I ❤️ the continuing work you're doing.  If I've been silent, it's only because I'm out of new ideas/problems, or you've already implemented everything (or plan to). 👏

**Comment by javiergutierrezchamorro** [comment]
Glad to hear!

**Comment by TPS** [comment]
Done in https://github.com/svn2github/nikkhokkho/commit/02358e7cf82c2cb9a7afcbbe704d0f5c02845e56.  Thanks!
