### ISSUE TITLE
AdvanceComp Updated

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#19]
@javiergutierrezchamorro: 
@amadvance has updated @ https://github.com/amadvance/advancecomp/releases/, including ***new*** Win64 binaries!  He may [update SF](https://sourceforge.net/projects/advancemame/files/advancecomp/) eventually.

**Comment by javiergutierrezchamorro** [comment]
Thanks. Will update it now.

**Comment by TPS** [comment]
https://github.com/svn2github/nikkhokkho/commit/14e5ee1bfc5a63c8f52699e01b77e0ac96449e0e
