### ISSUE TITLE
.ico (Icons) crash TruePNG

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#2]
Everytime I recompress .ico (icons), TruePNG crashes.  The rest of the tool-chain seems fine, though getting any results (i.e. actual byte-saving) seems spotty.

**Comment by javiergutierrezchamorro** [comment]
I am aware on that. Unfortunately tried contacting TruePNG developer without any luck.

**Comment by TPS** [comment]
Wouldn't it better just to remove TruePNG from the .ico chain until TruePNG gets fixed?

**Comment by javiergutierrezchamorro** [comment]
Problem is that it is not crashing on all ico files, at least according to my tests, and if they internaly use PNG compression gets improved by using TruePNG.

Is it crashing for you on all ico files, or only on some?

**Comment by TPS** [comment]
I've never found a .ico it _doesn't_ crash for me.

**Comment by TPS** [comment]
Just FYI:  According to http://x128.ho.ua/pngutils.html, TruePNG's been updated to 0.6.2.2 on April 3.  Maybe it helps this?

**Comment by javiergutierrezchamorro** [comment]
Exactly. Thanks.
TruePNG has been disabled as of r447.

**Comment by TPS** [comment]
I'm assuming just with .ico's, right?

Thanks!

**Comment by TPS** [comment]
It occurs to me, a better (but more labor-intensive) method to work around this is to [use ImageMagick](http://stackoverflow.com/questions/11423711/recipe-for-creating-windows-ico-files-with-imagemagick) or a [dedicated tool](http://www.winterdrache.de/freeware/png2ico/) to decompile .ico's to (a series of) .png's, run the .png chain on each (which should be reasonably quick, as I think even the HD icons top-out @ 32bit×256×256), & then recompile to feed the rest of the .ico chain.

**Comment by javiergutierrezchamorro** [comment]
Yes, only for ico file types (.ico and .spl extensions).
