### ISSUE TITLE
RFE/C: Newer FFMPEG Builds?

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#20]
@javiergutierrezchamorro The latest included in FO seem to be 3.3.3, but https://ffmpeg.zeranoe.com/builds lists 3.3.4 & daily binary releases in x32 & x64 static & shared library builds. These are the builds preferred by https://www.ffmpeg.org/download.html#build-windows & major frontends such as Avanti (http://www.avanti.arrozcru.org).  What do you think?

**Comment by javiergutierrezchamorro** [comment]
Thanks. It is now updated.

**Comment by TPS** [comment]
Of course, https://github.com/FFmpeg/FFmpeg/releases has the continually latest _sources_, but I dunno if you're willing to custom-compile optimized binaries.…

**Comment by TPS** [comment]
https://github.com/svn2github/nikkhokkho/commit/842445874dca2a189eb21a73403f88ef1b9fc291
