### ISSUE TITLE
RFC: Integration of ideas/tools from @pts's *sizeopt work

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#8]
@javiergutierrezchamorro: @pts has written a number of *sizeopt `python`  & `c/c++` programs that _might_ be worth getting some ideas from, especially in the way of new tools for the various (`pdf`, `jbig`/`jbig2`, & `jpg`) chains:
- https://github.com/pts/pdfsizeopt → https://github.com/pts/pdfsizeopt/blob/master/info.txt
- https://github.com/pts/pdfsizeopt-jbig2 → https://github.com/pts/pdfsizeopt-jbig2/blob/master/c.sh
- https://github.com/pts/pdfsizeopt-jpegtran → https://github.com/pts/pdfsizeopt-jpegtran/blob/master/c.sh
- https://github.com/pts/pdfsizeopt-jhead → https://github.com/pts/pdfsizeopt-jhead/blob/master/makefile-win32

Is anything here helpful?

https://code.google.com/archive/p/pdfsizeopt/ says this is GPL≥2.

**Comment by javiergutierrezchamorro** [comment]
Sounds interesting, but I am not able to find any Windows binaries on the releases section.

**Comment by TPS** [comment]
Try downloading everything from https://code.google.com/archive/p/pdfsizeopt/downloads, as I've no idea how long Google will keep that active.… 

@pts, could you put everything from that link, if not anything more recent, in https://github.com/pts/pdfsizeopt/releases?  Thanks!

**Comment by javiergutierrezchamorro** [comment]
Thanks. Was taking a look to the Python scripts, and seems that it is convertir de PDF to PostScript, and the optimizing standalone its resources (PNG and JPEG), which are then assembled again into PDF.

The idea is good, but it is too complex to be replicated on FileOptimizer. Also integrating it, it is not a good idea, since will make require the py interpreter.

**Comment by pts** [comment]
I wish you great success with FileOptimizer!

I've just copied the files from https://code.google.com/archive/p/pdfsizeopt/downloads to https://github.com/pts/pdfsizeopt/releases for your convenience. The Mac OS X binaries are quite outdated, you may want to recompile them. I don't have easy access to a Mac to do it myself. For the Linux i386 binaries (which also run on FreeBSD in Linux emulation mode) I can relatively easily provide the newest version (i.e. 1 hour of work for me) if there is a need.

pdfsizeopt not only has the Python interpreter as a dependency, it also depends on Ghostscript and some other tools (such as sam2p and jbig2). So it's relatively complicated the embed it or to use it as a library. I can help you to make it easier: we can discuss what you need and how much is achievable, and what I can do for you. Please note that I'm going to charge my hourly rate for this service, the first hour is free.

If the license is a problem, I can relicense pdfsizeopt for you under a different free license. But please note that you need to take a look at the license of the dependencies. sam2p is also in my control, I can relicense it for you, but for the rest you need to ask the owner. pdf22pnm is based on pdftopnm.

If you find another PDF optimizer which is easier to use than pdfsizeopt in FileOptimizer, please let me know.

**Comment by javiergutierrezchamorro** [comment]
Thank you for your offer @pts 

Ghostcript dependency is not a problem, since it is already included in FileOptimizer. As for the hourly rate, it would be OK when I would charge mine for FileOptimizer itself ;-)

**Comment by TPS** [comment]
@pts Thanks for the reply & importing the releases. ☺  I also appreciate your proposals, & wish you all good fortune. 🙇 

>and the optimizing standalone its resources (PNG and JPEG), which are then assembled again into PDF.
>
 The idea is good, but it is too complex to be replicated on FileOptimizer.

@javiergutierrezchamorro Right, in that sense it's like #6, so that's why I RFCed this. ☺  Close this (& maybe that?), at least for now?
