### ISSUE TITLE
Update pngwolf-zopfli

### ISSUE THREAD

**Issue by TPS** [javiergutierrezchamorro/nikkhokkho#9]
@javiergutierrezchamorro New binaries @ https://github.com/jibsen/pngwolf-zopfli/releases/

**Comment by javiergutierrezchamorro** [comment]
Thanks. It is done in r518: https://sourceforge.net/p/nikkhokkho/code/518/

**Comment by TPS** [comment]
Heh, I thought you were already using pngwolf-zopfli.  Thanks for the 🎩/T!

The commit here on GitHub is https://github.com/svn2github/nikkhokkho/commit/ae5c6023c3fe93e2608ac6fc7dad746ab471c85a.

**Comment by TPS** [comment]
Also, because it's compiled against OpenMP, it's now multi-threaded, which, I'm sure, is a very popular request for FileOptimizer as a whole.

**Comment by javiergutierrezchamorro** [comment]
Due to crashes on the x64 build of pngwolf-zopfli (https://sourceforge.net/p/nikkhokkho/discussion/fileoptimizer/thread/ad61af06/?limit=25) I will force FileOptimizer using the x86 build even on 64 bit systems.

**Comment by TPS** [comment]
That's bizarre.  I've run it on several thousand PNGs since the switch & no problem.

Anyway, I filed https://github.com/jibsen/pngwolf-zopfli/issues/2 to track this.  Can you point folks to it?

**Comment by TPS** [comment]
Wait, since https://github.com/svn2github/nikkhokkho/commit/3f216b39a4d02c1996275fa4c72928d91d56aba5 has _already_ landed, you won't be able to tell whether https://github.com/svn2github/nikkhokkho/commit/47f79e9eb2e364085410c59f8a84d1e935ffd556 fixes the problem, right?

**Comment by TPS** [comment]
@javiergutierrezchamorro I guess I'd consider https://sourceforge.net/p/nikkhokkho/discussion/fileoptimizer/thread/ad61af06/#2b98 by 1 of the OPs confirmation [this](https://github.com/javiergutierrezchamorro/nikkhokkho/issues/9#issuecomment-243999006) is solved via https://github.com/svn2github/nikkhokkho/commit/5243327a397d9fd593895f067281d0be33be3bf5, correct?  Or are we waiting for more?

**Comment by javiergutierrezchamorro** [comment]
Correct.
